/*
================================================================================
    SNOWFLAKE E2E OBSERVABILITY FRAMEWORK
    Version: 1.0
    Created: March 2026
================================================================================

EXECUTIVE SUMMARY
================================================================================
This framework provides comprehensive observability across 10 key domains:
    1. Platform Performance Monitoring
    2. Pipeline Reliability & Freshness Monitoring
    3. FinOps & Cost Intelligence
    4. Data Quality & Trust Metrics
    5. Security & Access Monitoring
    6. Metadata & Lineage Visibility
    7. User & Workload Behavior Insights
    8. Alerting & Automated Remediation
    9. Executive Dashboards & KPIs
    10. Governance, Automation & Standardization

ARCHITECTURE OVERVIEW
================================================================================
┌─────────────────────────────────────────────────────────────────────────────┐
│                        SNOWFLAKE OBSERVABILITY FRAMEWORK                     │
├─────────────────────────────────────────────────────────────────────────────┤
│  DATA SOURCES              │  PROCESSING LAYER        │  PRESENTATION LAYER │
│  ─────────────────────     │  ────────────────────    │  ───────────────────│
│  • SNOWFLAKE.ACCOUNT_USAGE │  • Dynamic Tables        │  • Snowsight        │
│  • SNOWFLAKE.ORGANIZATION_ │  • Materialized Views    │  • Streamlit Apps   │
│    USAGE                   │  • Scheduled Tasks       │  • BI Tools         │
│  • SNOWFLAKE.READER_USAGE  │  • Stored Procedures     │  • Alert Emails     │
│  • INFORMATION_SCHEMA      │  • UDFs                  │  • Webhooks         │
│  • Event Tables            │  • Alerts                │  • PagerDuty/Slack  │
│  • Custom Telemetry        │  • Streams               │  • API Endpoints    │
└─────────────────────────────────────────────────────────────────────────────┘

PREREQUISITES
================================================================================
- ACCOUNTADMIN role or equivalent permissions
- Access to SNOWFLAKE database (Account Usage views)
- Enterprise Edition (for some features like Data Quality Monitoring)
- Dedicated warehouse for observability workloads
================================================================================
*/

-- ============================================================================
-- SECTION 0: ENVIRONMENT SETUP
-- ============================================================================

USE DATABASE SNOWFLAKE_LEARNING_DB;
USE WAREHOUSE OBSERVABILITY_WH;

CREATE SCHEMA IF NOT EXISTS OBSERVABILITY;
USE SCHEMA OBSERVABILITY;

/*
================================================================================
SECTION 1: PLATFORM PERFORMANCE MONITORING
================================================================================
PURPOSE: Monitor warehouse performance, query execution, resource utilization,
         and identify bottlenecks across the Snowflake platform.

KEY METRICS:
- Warehouse utilization and queue times
- Query performance (duration, compilation, execution)
- Concurrency levels and scaling events
- Resource contention indicators

DATA SOURCES:
- SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_EVENTS_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
================================================================================
*/

-- 1.1 Warehouse Performance Summary (Last 7 Days)
CREATE OR REPLACE VIEW V_WAREHOUSE_PERFORMANCE_SUMMARY AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('day', START_TIME) AS REPORT_DATE,
    COUNT(*) AS TOTAL_QUERIES,
    AVG(TOTAL_ELAPSED_TIME)/1000 AS AVG_ELAPSED_SEC,
    MEDIAN(TOTAL_ELAPSED_TIME)/1000 AS MEDIAN_ELAPSED_SEC,
    MAX(TOTAL_ELAPSED_TIME)/1000 AS MAX_ELAPSED_SEC,
    AVG(QUEUED_OVERLOAD_TIME)/1000 AS AVG_QUEUE_SEC,
    SUM(CASE WHEN QUEUED_OVERLOAD_TIME > 0 THEN 1 ELSE 0 END) AS QUEUED_QUERY_COUNT,
    ROUND(SUM(CASE WHEN QUEUED_OVERLOAD_TIME > 0 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS QUEUE_PERCENTAGE,
    AVG(BYTES_SCANNED)/1024/1024/1024 AS AVG_GB_SCANNED,
    SUM(BYTES_SCANNED)/1024/1024/1024/1024 AS TOTAL_TB_SCANNED,
    AVG(ROWS_PRODUCED) AS AVG_ROWS_PRODUCED,
    COUNT(DISTINCT USER_NAME) AS UNIQUE_USERS,
    COUNT(DISTINCT QUERY_TAG) AS UNIQUE_QUERY_TAGS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND WAREHOUSE_NAME IS NOT NULL
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('day', START_TIME)
ORDER BY REPORT_DATE DESC, TOTAL_QUERIES DESC;

-- 1.2 Query Performance Distribution
CREATE OR REPLACE VIEW V_QUERY_PERFORMANCE_DISTRIBUTION AS
SELECT
    WAREHOUSE_NAME,
    CASE
        WHEN TOTAL_ELAPSED_TIME < 1000 THEN '< 1 sec'
        WHEN TOTAL_ELAPSED_TIME < 5000 THEN '1-5 sec'
        WHEN TOTAL_ELAPSED_TIME < 30000 THEN '5-30 sec'
        WHEN TOTAL_ELAPSED_TIME < 60000 THEN '30-60 sec'
        WHEN TOTAL_ELAPSED_TIME < 300000 THEN '1-5 min'
        WHEN TOTAL_ELAPSED_TIME < 900000 THEN '5-15 min'
        ELSE '> 15 min'
    END AS DURATION_BUCKET,
    COUNT(*) AS QUERY_COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY WAREHOUSE_NAME), 2) AS PERCENTAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND WAREHOUSE_NAME IS NOT NULL
GROUP BY WAREHOUSE_NAME, DURATION_BUCKET
ORDER BY WAREHOUSE_NAME, 
    CASE DURATION_BUCKET
        WHEN '< 1 sec' THEN 1
        WHEN '1-5 sec' THEN 2
        WHEN '5-30 sec' THEN 3
        WHEN '30-60 sec' THEN 4
        WHEN '1-5 min' THEN 5
        WHEN '5-15 min' THEN 6
        ELSE 7
    END;

-- 1.3 Long Running Queries Monitor
CREATE OR REPLACE VIEW V_LONG_RUNNING_QUERIES AS
SELECT
    QUERY_ID,
    USER_NAME,
    WAREHOUSE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    QUERY_TYPE,
    EXECUTION_STATUS,
    START_TIME,
    END_TIME,
    TOTAL_ELAPSED_TIME/1000/60 AS DURATION_MINUTES,
    QUEUED_OVERLOAD_TIME/1000 AS QUEUE_SECONDS,
    COMPILATION_TIME/1000 AS COMPILE_SECONDS,
    EXECUTION_TIME/1000 AS EXEC_SECONDS,
    BYTES_SCANNED/1024/1024/1024 AS GB_SCANNED,
    ROWS_PRODUCED,
    QUERY_TAG,
    LEFT(QUERY_TEXT, 500) AS QUERY_PREVIEW,
    ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND TOTAL_ELAPSED_TIME > 300000  -- > 5 minutes
ORDER BY TOTAL_ELAPSED_TIME DESC
LIMIT 100;

-- 1.4 Warehouse Scaling Events
CREATE OR REPLACE VIEW V_WAREHOUSE_SCALING_EVENTS AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('hour', TIMESTAMP) AS EVENT_HOUR,
    EVENT_NAME,
    EVENT_REASON,
    CLUSTER_NUMBER,
    COUNT(*) AS EVENT_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_EVENTS_HISTORY
WHERE TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('hour', TIMESTAMP), EVENT_NAME, EVENT_REASON, CLUSTER_NUMBER
ORDER BY EVENT_HOUR DESC;

-- 1.5 Query Compilation vs Execution Time Analysis
CREATE OR REPLACE VIEW V_COMPILATION_EXECUTION_ANALYSIS AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('hour', START_TIME) AS HOUR_BUCKET,
    COUNT(*) AS QUERY_COUNT,
    AVG(COMPILATION_TIME)/1000 AS AVG_COMPILE_SEC,
    AVG(EXECUTION_TIME)/1000 AS AVG_EXEC_SEC,
    AVG(QUEUED_PROVISIONING_TIME)/1000 AS AVG_QUEUE_PROVISION_SEC,
    AVG(QUEUED_REPAIR_TIME)/1000 AS AVG_QUEUE_REPAIR_SEC,
    AVG(QUEUED_OVERLOAD_TIME)/1000 AS AVG_QUEUE_OVERLOAD_SEC,
    ROUND(AVG(COMPILATION_TIME) * 100.0 / NULLIF(AVG(TOTAL_ELAPSED_TIME), 0), 2) AS COMPILE_PCT,
    ROUND(AVG(EXECUTION_TIME) * 100.0 / NULLIF(AVG(TOTAL_ELAPSED_TIME), 0), 2) AS EXEC_PCT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -3, CURRENT_TIMESTAMP())
    AND WAREHOUSE_NAME IS NOT NULL
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('hour', START_TIME)
ORDER BY HOUR_BUCKET DESC;

/*
================================================================================
SECTION 2: PIPELINE RELIABILITY & FRESHNESS MONITORING
================================================================================
PURPOSE: Track data pipeline health, detect stale data, monitor task/stream
         execution, and ensure SLA compliance for data freshness.

KEY METRICS:
- Task success/failure rates
- Data freshness (last update times)
- Stream lag and pending rows
- Dynamic table refresh status
- Pipeline latency and throughput

DATA SOURCES:
- SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY
- INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
================================================================================
*/

-- 2.1 Task Execution Summary
CREATE OR REPLACE VIEW V_TASK_EXECUTION_SUMMARY AS
SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    NAME AS TASK_NAME,
    STATE,
    DATE_TRUNC('day', SCHEDULED_TIME) AS SCHEDULED_DATE,
    COUNT(*) AS TOTAL_RUNS,
    SUM(CASE WHEN STATE = 'SUCCEEDED' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    SUM(CASE WHEN STATE = 'FAILED' THEN 1 ELSE 0 END) AS FAILURE_COUNT,
    SUM(CASE WHEN STATE = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED_COUNT,
    ROUND(SUM(CASE WHEN STATE = 'SUCCEEDED' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS SUCCESS_RATE,
    AVG(TIMESTAMPDIFF('second', SCHEDULED_TIME, COMPLETED_TIME)) AS AVG_DURATION_SEC,
    MAX(TIMESTAMPDIFF('second', SCHEDULED_TIME, COMPLETED_TIME)) AS MAX_DURATION_SEC
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE SCHEDULED_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY DATABASE_NAME, SCHEMA_NAME, NAME, STATE, DATE_TRUNC('day', SCHEDULED_TIME)
ORDER BY SCHEDULED_DATE DESC, FAILURE_COUNT DESC;

-- 2.2 Failed Tasks Detail
CREATE OR REPLACE VIEW V_FAILED_TASKS_DETAIL AS
SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    NAME AS TASK_NAME,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    STATE,
    ERROR_CODE,
    ERROR_MESSAGE,
    QUERY_ID,
    GRAPH_VERSION,
    RUN_ID
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE STATE = 'FAILED'
    AND SCHEDULED_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
ORDER BY SCHEDULED_TIME DESC;

-- 2.3 Table Freshness Monitor (Custom Implementation)
CREATE OR REPLACE VIEW V_TABLE_FRESHNESS AS
SELECT
    t.TABLE_CATALOG AS DATABASE_NAME,
    t.TABLE_SCHEMA AS SCHEMA_NAME,
    t.TABLE_NAME,
    t.TABLE_TYPE,
    t.ROW_COUNT,
    t.BYTES / 1024 / 1024 AS SIZE_MB,
    t.LAST_ALTERED AS LAST_DDL_CHANGE,
    TIMESTAMPDIFF('hour', t.LAST_ALTERED, CURRENT_TIMESTAMP()) AS HOURS_SINCE_LAST_CHANGE,
    CASE
        WHEN TIMESTAMPDIFF('hour', t.LAST_ALTERED, CURRENT_TIMESTAMP()) <= 1 THEN 'FRESH'
        WHEN TIMESTAMPDIFF('hour', t.LAST_ALTERED, CURRENT_TIMESTAMP()) <= 24 THEN 'RECENT'
        WHEN TIMESTAMPDIFF('hour', t.LAST_ALTERED, CURRENT_TIMESTAMP()) <= 168 THEN 'STALE'
        ELSE 'VERY_STALE'
    END AS FRESHNESS_STATUS
FROM SNOWFLAKE_LEARNING_DB.INFORMATION_SCHEMA.TABLES t
WHERE t.TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
ORDER BY HOURS_SINCE_LAST_CHANGE DESC;

-- 2.4 Copy History Summary (Data Ingestion)
CREATE OR REPLACE VIEW V_COPY_HISTORY_SUMMARY AS
SELECT
    TABLE_CATALOG_NAME AS DATABASE_NAME,
    TABLE_SCHEMA_NAME AS SCHEMA_NAME,
    TABLE_NAME,
    DATE_TRUNC('hour', LAST_LOAD_TIME) AS LOAD_HOUR,
    COUNT(*) AS LOAD_COUNT,
    SUM(ROW_COUNT) AS TOTAL_ROWS_LOADED,
    SUM(FILE_SIZE)/1024/1024 AS TOTAL_MB_LOADED,
    SUM(CASE WHEN STATUS = 'LOADED' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    SUM(CASE WHEN STATUS != 'LOADED' THEN 1 ELSE 0 END) AS ERROR_COUNT,
    COUNT(DISTINCT FILE_NAME) AS FILES_PROCESSED
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
WHERE LAST_LOAD_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY TABLE_CATALOG_NAME, TABLE_SCHEMA_NAME, TABLE_NAME, DATE_TRUNC('hour', LAST_LOAD_TIME)
ORDER BY LOAD_HOUR DESC;

-- 2.5 Snowpipe Performance
CREATE OR REPLACE VIEW V_SNOWPIPE_PERFORMANCE AS
SELECT
    PIPE_CATALOG_NAME AS DATABASE_NAME,
    PIPE_SCHEMA_NAME AS SCHEMA_NAME,
    PIPE_NAME,
    DATE_TRUNC('hour', START_TIME) AS HOUR_BUCKET,
    SUM(FILES_INSERTED) AS FILES_INSERTED,
    SUM(BYTES_INSERTED)/1024/1024 AS MB_INSERTED,
    SUM(CREDITS_USED) AS CREDITS_USED,
    AVG(BYTES_INSERTED)/NULLIF(AVG(FILES_INSERTED), 0)/1024 AS AVG_FILE_SIZE_KB
FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY PIPE_CATALOG_NAME, PIPE_SCHEMA_NAME, PIPE_NAME, DATE_TRUNC('hour', START_TIME)
ORDER BY HOUR_BUCKET DESC;

/*
================================================================================
SECTION 3: FINOPS & COST INTELLIGENCE
================================================================================
PURPOSE: Track credit consumption, identify cost drivers, optimize spending,
         and provide cost allocation across teams/projects.

KEY METRICS:
- Credit consumption by warehouse/user/query type
- Storage costs and growth trends
- Serverless feature costs
- Cost per query/workload
- Budget tracking and forecasting

DATA SOURCES:
- SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE
- SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
================================================================================
*/

-- 3.1 Credit Consumption by Warehouse
CREATE OR REPLACE VIEW V_CREDIT_CONSUMPTION_WAREHOUSE AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('day', START_TIME) AS USAGE_DATE,
    SUM(CREDITS_USED) AS TOTAL_CREDITS,
    SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS,
    AVG(CREDITS_USED) AS AVG_HOURLY_CREDITS,
    COUNT(DISTINCT DATE_TRUNC('hour', START_TIME)) AS ACTIVE_HOURS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('day', START_TIME)
ORDER BY USAGE_DATE DESC, TOTAL_CREDITS DESC;

-- 3.2 Credit Consumption by User
CREATE OR REPLACE VIEW V_CREDIT_CONSUMPTION_USER AS
SELECT
    USER_NAME,
    DATE_TRUNC('day', START_TIME) AS USAGE_DATE,
    WAREHOUSE_NAME,
    COUNT(*) AS QUERY_COUNT,
    SUM(TOTAL_ELAPSED_TIME)/1000/60/60 AS TOTAL_HOURS,
    ROUND(SUM(CREDITS_USED_CLOUD_SERVICES), 4) AS CLOUD_SERVICES_CREDITS,
    SUM(BYTES_SCANNED)/1024/1024/1024/1024 AS TB_SCANNED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    AND USER_NAME IS NOT NULL
GROUP BY USER_NAME, DATE_TRUNC('day', START_TIME), WAREHOUSE_NAME
ORDER BY USAGE_DATE DESC, QUERY_COUNT DESC;

-- 3.3 Serverless Feature Costs
CREATE OR REPLACE VIEW V_SERVERLESS_COSTS AS
SELECT
    SERVICE_TYPE,
    DATE_TRUNC('day', START_TIME) AS USAGE_DATE,
    SUM(CREDITS_USED) AS TOTAL_CREDITS,
    COUNT(*) AS USAGE_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY SERVICE_TYPE, DATE_TRUNC('day', START_TIME)
ORDER BY USAGE_DATE DESC, TOTAL_CREDITS DESC;

-- 3.4 Storage Usage Trends
CREATE OR REPLACE VIEW V_STORAGE_USAGE_TRENDS AS
SELECT
    DATE_TRUNC('day', USAGE_DATE) AS REPORT_DATE,
    ROUND(AVG(STORAGE_BYTES)/1024/1024/1024/1024, 4) AS AVG_STORAGE_TB,
    ROUND(AVG(STAGE_BYTES)/1024/1024/1024/1024, 4) AS AVG_STAGE_TB,
    ROUND(AVG(FAILSAFE_BYTES)/1024/1024/1024/1024, 4) AS AVG_FAILSAFE_TB,
    ROUND((AVG(STORAGE_BYTES) + AVG(STAGE_BYTES) + AVG(FAILSAFE_BYTES))/1024/1024/1024/1024, 4) AS TOTAL_TB
FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE
WHERE USAGE_DATE >= DATEADD('day', -90, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('day', USAGE_DATE)
ORDER BY REPORT_DATE DESC;

-- 3.5 Database Storage Breakdown
CREATE OR REPLACE VIEW V_DATABASE_STORAGE_BREAKDOWN AS
SELECT
    DATABASE_NAME,
    DATE_TRUNC('day', USAGE_DATE) AS REPORT_DATE,
    ROUND(AVG(AVERAGE_DATABASE_BYTES)/1024/1024/1024, 2) AS AVG_DB_SIZE_GB,
    ROUND(AVG(AVERAGE_FAILSAFE_BYTES)/1024/1024/1024, 2) AS AVG_FAILSAFE_GB,
    ROUND((AVG(AVERAGE_DATABASE_BYTES) + AVG(AVERAGE_FAILSAFE_BYTES))/1024/1024/1024, 2) AS TOTAL_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE USAGE_DATE >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    AND DATABASE_NAME IS NOT NULL
GROUP BY DATABASE_NAME, DATE_TRUNC('day', USAGE_DATE)
ORDER BY REPORT_DATE DESC, TOTAL_GB DESC;

-- 3.6 Cost Per Query Analysis
CREATE OR REPLACE VIEW V_COST_PER_QUERY AS
SELECT
    QUERY_TYPE,
    USER_NAME,
    WAREHOUSE_NAME,
    DATE_TRUNC('day', START_TIME) AS QUERY_DATE,
    COUNT(*) AS QUERY_COUNT,
    AVG(TOTAL_ELAPSED_TIME)/1000 AS AVG_DURATION_SEC,
    SUM(BYTES_SCANNED)/1024/1024/1024 AS TOTAL_GB_SCANNED,
    ROUND(SUM(CREDITS_USED_CLOUD_SERVICES), 4) AS CLOUD_CREDITS,
    ROUND(SUM(CREDITS_USED_CLOUD_SERVICES)/NULLIF(COUNT(*), 0), 6) AS AVG_CREDIT_PER_QUERY
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND QUERY_TYPE NOT IN ('UNKNOWN')
GROUP BY QUERY_TYPE, USER_NAME, WAREHOUSE_NAME, DATE_TRUNC('day', START_TIME)
ORDER BY CLOUD_CREDITS DESC;

-- 3.7 Monthly Cost Summary with Trending
CREATE OR REPLACE VIEW V_MONTHLY_COST_SUMMARY AS
SELECT
    DATE_TRUNC('month', START_TIME) AS MONTH,
    SUM(CREDITS_USED) AS TOTAL_CREDITS,
    SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICES_CREDITS,
    LAG(SUM(CREDITS_USED)) OVER (ORDER BY DATE_TRUNC('month', START_TIME)) AS PREV_MONTH_CREDITS,
    ROUND((SUM(CREDITS_USED) - LAG(SUM(CREDITS_USED)) OVER (ORDER BY DATE_TRUNC('month', START_TIME))) 
        / NULLIF(LAG(SUM(CREDITS_USED)) OVER (ORDER BY DATE_TRUNC('month', START_TIME)), 0) * 100, 2) AS MOM_CHANGE_PCT
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('month', -12, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('month', START_TIME)
ORDER BY MONTH DESC;

/*
================================================================================
SECTION 4: DATA QUALITY & TRUST METRICS
================================================================================
PURPOSE: Monitor data quality dimensions (completeness, accuracy, consistency),
         track data quality scores, and detect anomalies.

KEY METRICS:
- Null/missing value rates
- Duplicate detection
- Schema drift detection
- Data anomaly detection
- Quality score calculations

DATA SOURCES:
- Custom DMF (Data Metric Functions)
- SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS_RAW (Enterprise)
- Custom validation queries
================================================================================
*/

-- 4.1 Data Quality Framework Table (Configuration)
CREATE TABLE IF NOT EXISTS T_DATA_QUALITY_RULES (
    RULE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    DATABASE_NAME VARCHAR(255),
    SCHEMA_NAME VARCHAR(255),
    TABLE_NAME VARCHAR(255),
    COLUMN_NAME VARCHAR(255),
    RULE_TYPE VARCHAR(50),  -- NULL_CHECK, UNIQUE_CHECK, RANGE_CHECK, PATTERN_CHECK, FRESHNESS_CHECK
    RULE_DEFINITION VARCHAR(4000),
    THRESHOLD_WARNING NUMBER,
    THRESHOLD_CRITICAL NUMBER,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4.2 Data Quality Results Log
CREATE TABLE IF NOT EXISTS T_DATA_QUALITY_RESULTS (
    RESULT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RULE_ID NUMBER,
    EXECUTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METRIC_VALUE NUMBER,
    TOTAL_ROWS NUMBER,
    FAILED_ROWS NUMBER,
    PASS_RATE NUMBER,
    STATUS VARCHAR(20),  -- PASS, WARNING, CRITICAL
    DETAILS VARIANT
);

-- 4.3 Procedure: Execute Data Quality Check
CREATE OR REPLACE PROCEDURE SP_RUN_DATA_QUALITY_CHECK(
    P_DATABASE VARCHAR,
    P_SCHEMA VARCHAR,
    P_TABLE VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    V_RESULT VARCHAR DEFAULT 'Data quality check completed';
    V_TOTAL_ROWS NUMBER;
    V_NULL_COUNT NUMBER;
BEGIN
    -- Get total row count
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || P_DATABASE || '.' || P_SCHEMA || '.' || P_TABLE 
        INTO :V_TOTAL_ROWS;
    
    RETURN V_RESULT || ' for ' || P_DATABASE || '.' || P_SCHEMA || '.' || P_TABLE || 
           ' (Total Rows: ' || V_TOTAL_ROWS || ')';
END;
$$;

-- 4.4 Schema Change Detection View
CREATE OR REPLACE VIEW V_SCHEMA_CHANGES AS
SELECT
    EVENT_TIMESTAMP,
    USER_NAME,
    QUERY_TYPE,
    DATABASE_NAME,
    SCHEMA_NAME,
    QUERY_TEXT,
    CASE
        WHEN QUERY_TYPE IN ('CREATE_TABLE', 'CREATE_VIEW', 'CREATE_SCHEMA') THEN 'OBJECT_CREATED'
        WHEN QUERY_TYPE IN ('DROP_TABLE', 'DROP_VIEW', 'DROP_SCHEMA') THEN 'OBJECT_DROPPED'
        WHEN QUERY_TYPE IN ('ALTER_TABLE', 'RENAME_TABLE') THEN 'OBJECT_MODIFIED'
        ELSE 'OTHER'
    END AS CHANGE_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TYPE IN (
    'CREATE_TABLE', 'CREATE_VIEW', 'CREATE_SCHEMA', 'CREATE_DATABASE',
    'DROP_TABLE', 'DROP_VIEW', 'DROP_SCHEMA', 'DROP_DATABASE',
    'ALTER_TABLE', 'RENAME_TABLE', 'ALTER_VIEW'
)
AND START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIMESTAMP DESC;

-- 4.5 Table Statistics Summary
CREATE OR REPLACE VIEW V_TABLE_STATISTICS AS
SELECT
    TABLE_CATALOG AS DATABASE_NAME,
    TABLE_SCHEMA AS SCHEMA_NAME,
    TABLE_NAME,
    ROW_COUNT,
    BYTES/1024/1024 AS SIZE_MB,
    CLUSTERING_KEY,
    IS_TRANSIENT,
    RETENTION_TIME,
    LAST_ALTERED,
    AUTO_CLUSTERING_ON,
    COMMENT
FROM SNOWFLAKE_LEARNING_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
    AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
ORDER BY BYTES DESC NULLS LAST;

/*
================================================================================
SECTION 5: SECURITY & ACCESS MONITORING
================================================================================
PURPOSE: Monitor authentication, authorization, data access patterns,
         detect anomalies, and ensure compliance.

KEY METRICS:
- Login success/failure rates
- Access patterns by user/role
- Sensitive data access tracking
- Role/privilege changes
- Network policy violations

DATA SOURCES:
- SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS
- SNOWFLAKE.ACCOUNT_USAGE.SESSIONS
================================================================================
*/

-- 5.1 Login Activity Summary
CREATE OR REPLACE VIEW V_LOGIN_ACTIVITY AS
SELECT
    USER_NAME,
    DATE_TRUNC('day', EVENT_TIMESTAMP) AS LOGIN_DATE,
    REPORTED_CLIENT_TYPE,
    FIRST_AUTHENTICATION_FACTOR,
    IS_SUCCESS,
    COUNT(*) AS LOGIN_COUNT,
    COUNT(DISTINCT CLIENT_IP) AS UNIQUE_IPS,
    MIN(EVENT_TIMESTAMP) AS FIRST_LOGIN,
    MAX(EVENT_TIMESTAMP) AS LAST_LOGIN
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY USER_NAME, DATE_TRUNC('day', EVENT_TIMESTAMP), REPORTED_CLIENT_TYPE, 
         FIRST_AUTHENTICATION_FACTOR, IS_SUCCESS
ORDER BY LOGIN_DATE DESC, LOGIN_COUNT DESC;

-- 5.2 Failed Login Attempts (Security Alert)
CREATE OR REPLACE VIEW V_FAILED_LOGINS AS
SELECT
    USER_NAME,
    EVENT_TIMESTAMP,
    CLIENT_IP,
    REPORTED_CLIENT_TYPE,
    ERROR_CODE,
    ERROR_MESSAGE,
    FIRST_AUTHENTICATION_FACTOR
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE IS_SUCCESS = 'NO'
    AND EVENT_TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIMESTAMP DESC;

-- 5.3 Data Access Patterns
CREATE OR REPLACE VIEW V_DATA_ACCESS_PATTERNS AS
SELECT
    USER_NAME,
    DATE_TRUNC('hour', QUERY_START_TIME) AS ACCESS_HOUR,
    DIRECT_OBJECTS_ACCESSED,
    BASE_OBJECTS_ACCESSED,
    COUNT(*) AS ACCESS_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY USER_NAME, DATE_TRUNC('hour', QUERY_START_TIME), DIRECT_OBJECTS_ACCESSED, BASE_OBJECTS_ACCESSED
ORDER BY ACCESS_HOUR DESC;

-- 5.4 Role and Privilege Changes
CREATE OR REPLACE VIEW V_PRIVILEGE_CHANGES AS
SELECT
    START_TIME AS CHANGE_TIME,
    USER_NAME AS CHANGED_BY,
    QUERY_TYPE,
    DATABASE_NAME,
    SCHEMA_NAME,
    QUERY_TEXT,
    EXECUTION_STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TYPE IN ('GRANT', 'REVOKE', 'CREATE_ROLE', 'DROP_ROLE', 'ALTER_USER')
    AND START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC;

-- 5.5 Session Analysis
CREATE OR REPLACE VIEW V_SESSION_ANALYSIS AS
SELECT
    USER_NAME,
    DATE_TRUNC('day', CREATED_ON) AS SESSION_DATE,
    CLIENT_APPLICATION_ID,
    COUNT(*) AS SESSION_COUNT,
    AVG(TIMESTAMPDIFF('minute', CREATED_ON, COALESCE(AUTHENTICATION_METHOD, CREATED_ON))) AS AVG_SESSION_DURATION_MIN
FROM SNOWFLAKE.ACCOUNT_USAGE.SESSIONS
WHERE CREATED_ON >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY USER_NAME, DATE_TRUNC('day', CREATED_ON), CLIENT_APPLICATION_ID
ORDER BY SESSION_DATE DESC;

-- 5.6 User Role Assignments
CREATE OR REPLACE VIEW V_USER_ROLE_MATRIX AS
SELECT
    GRANTEE_NAME AS USER_NAME,
    ROLE AS ASSIGNED_ROLE,
    GRANTED_BY,
    CREATED_ON,
    DELETED_ON,
    CASE WHEN DELETED_ON IS NULL THEN 'ACTIVE' ELSE 'REVOKED' END AS STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS
WHERE GRANTED_ON = 'ROLE'
ORDER BY GRANTEE_NAME, CREATED_ON DESC;

/*
================================================================================
SECTION 6: METADATA & LINEAGE VISIBILITY
================================================================================
PURPOSE: Track data lineage, object dependencies, impact analysis,
         and provide comprehensive metadata management.

KEY METRICS:
- Column-level lineage
- Object dependencies
- Impact analysis for changes
- Metadata completeness
- Tag coverage

DATA SOURCES:
- SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES
- SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
================================================================================
*/

-- 6.1 Object Dependencies
CREATE OR REPLACE VIEW V_OBJECT_DEPENDENCIES AS
SELECT
    REFERENCING_DATABASE,
    REFERENCING_SCHEMA,
    REFERENCING_OBJECT_NAME,
    REFERENCING_OBJECT_DOMAIN,
    REFERENCED_DATABASE,
    REFERENCED_SCHEMA,
    REFERENCED_OBJECT_NAME,
    REFERENCED_OBJECT_DOMAIN,
    DEPENDENCY_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES
ORDER BY REFERENCING_DATABASE, REFERENCING_SCHEMA, REFERENCING_OBJECT_NAME;

-- 6.2 Column-Level Lineage from Access History
CREATE OR REPLACE VIEW V_COLUMN_LINEAGE AS
SELECT
    USER_NAME,
    QUERY_ID,
    QUERY_START_TIME,
    DIRECT_OBJECTS_ACCESSED,
    BASE_OBJECTS_ACCESSED,
    OBJECTS_MODIFIED,
    OBJECT_MODIFIED_BY_DDL,
    POLICIES_REFERENCED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND (ARRAY_SIZE(DIRECT_OBJECTS_ACCESSED) > 0 OR ARRAY_SIZE(OBJECTS_MODIFIED) > 0)
ORDER BY QUERY_START_TIME DESC;

-- 6.3 Tag Coverage Analysis
CREATE OR REPLACE VIEW V_TAG_COVERAGE AS
SELECT
    TAG_DATABASE,
    TAG_SCHEMA,
    TAG_NAME,
    DOMAIN AS OBJECT_TYPE,
    COUNT(*) AS TAGGED_OBJECTS,
    COUNT(DISTINCT OBJECT_DATABASE || '.' || OBJECT_SCHEMA) AS TAGGED_SCHEMAS
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE DELETED IS NULL
GROUP BY TAG_DATABASE, TAG_SCHEMA, TAG_NAME, DOMAIN
ORDER BY TAGGED_OBJECTS DESC;

-- 6.4 Object Catalog Summary
CREATE OR REPLACE VIEW V_OBJECT_CATALOG AS
SELECT
    'DATABASE' AS OBJECT_TYPE,
    DATABASE_NAME AS OBJECT_NAME,
    NULL AS PARENT_SCHEMA,
    DATABASE_NAME AS PARENT_DATABASE,
    CREATED AS CREATED_DATE,
    LAST_ALTERED,
    COMMENT
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASES
WHERE DELETED IS NULL

UNION ALL

SELECT
    'SCHEMA' AS OBJECT_TYPE,
    SCHEMA_NAME AS OBJECT_NAME,
    CATALOG_NAME AS PARENT_SCHEMA,
    CATALOG_NAME AS PARENT_DATABASE,
    CREATED AS CREATED_DATE,
    LAST_ALTERED,
    COMMENT
FROM SNOWFLAKE.ACCOUNT_USAGE.SCHEMATA
WHERE DELETED IS NULL

UNION ALL

SELECT
    TABLE_TYPE AS OBJECT_TYPE,
    TABLE_NAME AS OBJECT_NAME,
    TABLE_SCHEMA AS PARENT_SCHEMA,
    TABLE_CATALOG AS PARENT_DATABASE,
    CREATED AS CREATED_DATE,
    LAST_ALTERED,
    COMMENT
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES
WHERE DELETED IS NULL

UNION ALL

SELECT
    'VIEW' AS OBJECT_TYPE,
    TABLE_NAME AS OBJECT_NAME,
    TABLE_SCHEMA AS PARENT_SCHEMA,
    TABLE_CATALOG AS PARENT_DATABASE,
    CREATED AS CREATED_DATE,
    LAST_ALTERED,
    COMMENT
FROM SNOWFLAKE.ACCOUNT_USAGE.VIEWS
WHERE DELETED IS NULL;

/*
================================================================================
SECTION 7: USER & WORKLOAD BEHAVIOR INSIGHTS
================================================================================
PURPOSE: Analyze user behavior patterns, workload distribution,
         identify optimization opportunities, and capacity planning.

KEY METRICS:
- User activity patterns
- Peak usage times
- Query patterns by type/complexity
- Resource consumption by workload
- Concurrency analysis

DATA SOURCES:
- SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY
- SNOWFLAKE.ACCOUNT_USAGE.SESSIONS
================================================================================
*/

-- 7.1 User Activity Heatmap (By Hour)
CREATE OR REPLACE VIEW V_USER_ACTIVITY_HEATMAP AS
SELECT
    USER_NAME,
    DAYOFWEEK(START_TIME) AS DAY_OF_WEEK,
    HOUR(START_TIME) AS HOUR_OF_DAY,
    COUNT(*) AS QUERY_COUNT,
    AVG(TOTAL_ELAPSED_TIME)/1000 AS AVG_DURATION_SEC,
    SUM(BYTES_SCANNED)/1024/1024/1024 AS GB_SCANNED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY USER_NAME, DAYOFWEEK(START_TIME), HOUR(START_TIME)
ORDER BY USER_NAME, DAY_OF_WEEK, HOUR_OF_DAY;

-- 7.2 Query Type Distribution
CREATE OR REPLACE VIEW V_QUERY_TYPE_DISTRIBUTION AS
SELECT
    QUERY_TYPE,
    DATE_TRUNC('day', START_TIME) AS QUERY_DATE,
    COUNT(*) AS QUERY_COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY DATE_TRUNC('day', START_TIME)), 2) AS PERCENTAGE,
    AVG(TOTAL_ELAPSED_TIME)/1000 AS AVG_DURATION_SEC,
    SUM(BYTES_SCANNED)/1024/1024/1024 AS TOTAL_GB_SCANNED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY QUERY_TYPE, DATE_TRUNC('day', START_TIME)
ORDER BY QUERY_DATE DESC, QUERY_COUNT DESC;

-- 7.3 Workload Patterns by Query Tag
CREATE OR REPLACE VIEW V_WORKLOAD_BY_QUERY_TAG AS
SELECT
    COALESCE(QUERY_TAG, 'UNTAGGED') AS QUERY_TAG,
    COUNT(*) AS QUERY_COUNT,
    COUNT(DISTINCT USER_NAME) AS UNIQUE_USERS,
    AVG(TOTAL_ELAPSED_TIME)/1000 AS AVG_DURATION_SEC,
    SUM(BYTES_SCANNED)/1024/1024/1024/1024 AS TB_SCANNED,
    SUM(ROWS_PRODUCED) AS TOTAL_ROWS_PRODUCED,
    ROUND(SUM(CREDITS_USED_CLOUD_SERVICES), 4) AS CLOUD_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY COALESCE(QUERY_TAG, 'UNTAGGED')
ORDER BY QUERY_COUNT DESC;

-- 7.4 Concurrent Query Analysis
CREATE OR REPLACE VIEW V_CONCURRENCY_ANALYSIS AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('minute', START_TIME) AS MINUTE_BUCKET,
    COUNT(*) AS CONCURRENT_QUERIES,
    AVG(QUEUED_OVERLOAD_TIME)/1000 AS AVG_QUEUE_SEC,
    MAX(QUEUED_OVERLOAD_TIME)/1000 AS MAX_QUEUE_SEC
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
    AND WAREHOUSE_NAME IS NOT NULL
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('minute', START_TIME)
HAVING COUNT(*) > 5
ORDER BY MINUTE_BUCKET DESC;

-- 7.5 User Engagement Score
CREATE OR REPLACE VIEW V_USER_ENGAGEMENT_SCORE AS
SELECT
    USER_NAME,
    COUNT(*) AS TOTAL_QUERIES,
    COUNT(DISTINCT DATE_TRUNC('day', START_TIME)) AS ACTIVE_DAYS,
    COUNT(DISTINCT WAREHOUSE_NAME) AS WAREHOUSES_USED,
    COUNT(DISTINCT DATABASE_NAME) AS DATABASES_ACCESSED,
    SUM(BYTES_SCANNED)/1024/1024/1024 AS TOTAL_GB_SCANNED,
    AVG(TOTAL_ELAPSED_TIME)/1000 AS AVG_QUERY_DURATION_SEC,
    ROUND(
        (COUNT(*) * 0.3) +
        (COUNT(DISTINCT DATE_TRUNC('day', START_TIME)) * 2) +
        (COUNT(DISTINCT DATABASE_NAME) * 1.5)
    , 2) AS ENGAGEMENT_SCORE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    AND USER_NAME IS NOT NULL
GROUP BY USER_NAME
ORDER BY ENGAGEMENT_SCORE DESC;

/*
================================================================================
SECTION 8: ALERTING & AUTOMATED REMEDIATION
================================================================================
PURPOSE: Set up proactive alerts, automated responses, and
         notification systems for critical events.

KEY METRICS:
- Alert trigger conditions
- Alert frequency and patterns
- Response times
- Remediation success rates

DATA SOURCES:
- Snowflake Alerts (Native Feature)
- Custom monitoring tables
- Event triggers
================================================================================
*/

-- 8.1 Alert Configuration Table
CREATE TABLE IF NOT EXISTS T_ALERT_CONFIG (
    ALERT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ALERT_NAME VARCHAR(255),
    ALERT_CATEGORY VARCHAR(50),  -- PERFORMANCE, SECURITY, COST, DATA_QUALITY, PIPELINE
    ALERT_CONDITION VARCHAR(4000),
    THRESHOLD_VALUE NUMBER,
    SEVERITY VARCHAR(20),  -- LOW, MEDIUM, HIGH, CRITICAL
    NOTIFICATION_CHANNEL VARCHAR(50),  -- EMAIL, SLACK, WEBHOOK
    NOTIFICATION_TARGET VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    COOLDOWN_MINUTES NUMBER DEFAULT 60,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 8.2 Alert History Log
CREATE TABLE IF NOT EXISTS T_ALERT_HISTORY (
    LOG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ALERT_ID NUMBER,
    ALERT_NAME VARCHAR(255),
    TRIGGERED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METRIC_VALUE NUMBER,
    THRESHOLD_VALUE NUMBER,
    SEVERITY VARCHAR(20),
    STATUS VARCHAR(20),  -- TRIGGERED, ACKNOWLEDGED, RESOLVED
    RESOLVED_AT TIMESTAMP_NTZ,
    NOTES VARCHAR(4000)
);

-- 8.3 Alert: Long Running Query Detection
CREATE OR REPLACE ALERT ALERT_LONG_RUNNING_QUERY
    WAREHOUSE = OBSERVABILITY_WH
    SCHEDULE = '5 MINUTE'
    IF (EXISTS (
        SELECT 1
        FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
        WHERE START_TIME >= DATEADD('minute', -10, CURRENT_TIMESTAMP())
            AND TOTAL_ELAPSED_TIME > 600000  -- 10 minutes
            AND EXECUTION_STATUS = 'RUNNING'
    ))
    THEN
        INSERT INTO SNOWFLAKE_LEARNING_DB.OBSERVABILITY.T_ALERT_HISTORY 
            (ALERT_NAME, SEVERITY, STATUS, NOTES)
        VALUES ('LONG_RUNNING_QUERY', 'HIGH', 'TRIGGERED', 'Query running > 10 minutes detected');

-- 8.4 Alert: Failed Task Detection
CREATE OR REPLACE ALERT ALERT_FAILED_TASK
    WAREHOUSE = OBSERVABILITY_WH
    SCHEDULE = '15 MINUTE'
    IF (EXISTS (
        SELECT 1
        FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
        WHERE SCHEDULED_TIME >= DATEADD('minute', -20, CURRENT_TIMESTAMP())
            AND STATE = 'FAILED'
    ))
    THEN
        INSERT INTO SNOWFLAKE_LEARNING_DB.OBSERVABILITY.T_ALERT_HISTORY 
            (ALERT_NAME, SEVERITY, STATUS, NOTES)
        VALUES ('FAILED_TASK', 'CRITICAL', 'TRIGGERED', 'Task failure detected');

-- 8.5 Alert: High Credit Consumption
CREATE OR REPLACE ALERT ALERT_HIGH_CREDIT_USAGE
    WAREHOUSE = OBSERVABILITY_WH
    SCHEDULE = '60 MINUTE'
    IF (EXISTS (
        SELECT 1
        FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
        WHERE START_TIME >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
        GROUP BY WAREHOUSE_NAME
        HAVING SUM(CREDITS_USED) > 10  -- Adjust threshold as needed
    ))
    THEN
        INSERT INTO SNOWFLAKE_LEARNING_DB.OBSERVABILITY.T_ALERT_HISTORY 
            (ALERT_NAME, SEVERITY, STATUS, NOTES)
        VALUES ('HIGH_CREDIT_USAGE', 'MEDIUM', 'TRIGGERED', 'Hourly credit usage exceeded threshold');

-- 8.6 Alert: Failed Login Attempts
CREATE OR REPLACE ALERT ALERT_FAILED_LOGINS
    WAREHOUSE = OBSERVABILITY_WH
    SCHEDULE = '15 MINUTE'
    IF (EXISTS (
        SELECT 1
        FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
        WHERE EVENT_TIMESTAMP >= DATEADD('minute', -20, CURRENT_TIMESTAMP())
            AND IS_SUCCESS = 'NO'
        GROUP BY USER_NAME
        HAVING COUNT(*) >= 5  -- 5+ failed attempts
    ))
    THEN
        INSERT INTO SNOWFLAKE_LEARNING_DB.OBSERVABILITY.T_ALERT_HISTORY 
            (ALERT_NAME, SEVERITY, STATUS, NOTES)
        VALUES ('FAILED_LOGIN_ATTEMPTS', 'CRITICAL', 'TRIGGERED', 'Multiple failed login attempts detected');

-- 8.7 Alert: Queue Time Spike
CREATE OR REPLACE ALERT ALERT_QUEUE_TIME_SPIKE
    WAREHOUSE = OBSERVABILITY_WH
    SCHEDULE = '10 MINUTE'
    IF (EXISTS (
        SELECT 1
        FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
        WHERE START_TIME >= DATEADD('minute', -15, CURRENT_TIMESTAMP())
            AND QUEUED_OVERLOAD_TIME > 60000  -- 1 minute queue time
    ))
    THEN
        INSERT INTO SNOWFLAKE_LEARNING_DB.OBSERVABILITY.T_ALERT_HISTORY 
            (ALERT_NAME, SEVERITY, STATUS, NOTES)
        VALUES ('QUEUE_TIME_SPIKE', 'HIGH', 'TRIGGERED', 'High queue times detected');

-- Enable Alerts (Run these separately to activate)
-- ALTER ALERT ALERT_LONG_RUNNING_QUERY RESUME;
-- ALTER ALERT ALERT_FAILED_TASK RESUME;
-- ALTER ALERT ALERT_HIGH_CREDIT_USAGE RESUME;
-- ALTER ALERT ALERT_FAILED_LOGINS RESUME;
-- ALTER ALERT ALERT_QUEUE_TIME_SPIKE RESUME;

/*
================================================================================
SECTION 9: EXECUTIVE DASHBOARDS & KPIs
================================================================================
PURPOSE: Provide high-level KPIs and metrics for executive reporting,
         trend analysis, and strategic decision making.

KEY METRICS:
- Platform health score
- Cost efficiency metrics
- SLA compliance
- Growth trends
- ROI indicators

DATA SOURCES:
- All Account Usage views
- Aggregated metrics from other modules
================================================================================
*/

-- 9.1 Platform Health Score
CREATE OR REPLACE VIEW V_PLATFORM_HEALTH_SCORE AS
WITH metrics AS (
    SELECT
        -- Query Success Rate
        ROUND(SUM(CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0 / 
              NULLIF(COUNT(*), 0), 2) AS query_success_rate,
        -- Average Queue Time (target: < 5 seconds = 100 score)
        AVG(QUEUED_OVERLOAD_TIME)/1000 AS avg_queue_sec,
        -- Query count for volume
        COUNT(*) AS total_queries
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
),
task_metrics AS (
    SELECT
        ROUND(SUM(CASE WHEN STATE = 'SUCCEEDED' THEN 1 ELSE 0 END) * 100.0 / 
              NULLIF(COUNT(*), 0), 2) AS task_success_rate
    FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
    WHERE SCHEDULED_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
),
login_metrics AS (
    SELECT
        ROUND(SUM(CASE WHEN IS_SUCCESS = 'YES' THEN 1 ELSE 0 END) * 100.0 / 
              NULLIF(COUNT(*), 0), 2) AS login_success_rate
    FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
    WHERE EVENT_TIMESTAMP >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
)
SELECT
    CURRENT_TIMESTAMP() AS REPORT_TIME,
    '24 Hours' AS PERIOD,
    m.query_success_rate AS QUERY_SUCCESS_RATE,
    COALESCE(t.task_success_rate, 100) AS TASK_SUCCESS_RATE,
    l.login_success_rate AS LOGIN_SUCCESS_RATE,
    m.avg_queue_sec AS AVG_QUEUE_SECONDS,
    m.total_queries AS TOTAL_QUERIES,
    -- Overall Health Score (weighted average)
    ROUND(
        (m.query_success_rate * 0.4) +
        (COALESCE(t.task_success_rate, 100) * 0.3) +
        (l.login_success_rate * 0.2) +
        (GREATEST(0, 100 - (m.avg_queue_sec * 2)) * 0.1)
    , 2) AS OVERALL_HEALTH_SCORE
FROM metrics m
CROSS JOIN task_metrics t
CROSS JOIN login_metrics l;

-- 9.2 Executive Summary KPIs
CREATE OR REPLACE VIEW V_EXECUTIVE_SUMMARY AS
SELECT
    'DAILY' AS PERIOD,
    CURRENT_DATE() AS REPORT_DATE,
    
    -- Volume Metrics
    (SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY 
     WHERE START_TIME >= DATEADD('day', -1, CURRENT_TIMESTAMP())) AS QUERIES_24H,
    
    (SELECT COUNT(DISTINCT USER_NAME) FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY 
     WHERE START_TIME >= DATEADD('day', -1, CURRENT_TIMESTAMP())) AS ACTIVE_USERS_24H,
    
    -- Cost Metrics
    (SELECT ROUND(SUM(CREDITS_USED), 2) FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY 
     WHERE START_TIME >= DATEADD('day', -1, CURRENT_TIMESTAMP())) AS CREDITS_24H,
    
    (SELECT ROUND(SUM(CREDITS_USED), 2) FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY 
     WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())) AS CREDITS_30D,
    
    -- Performance Metrics
    (SELECT ROUND(AVG(TOTAL_ELAPSED_TIME)/1000, 2) FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY 
     WHERE START_TIME >= DATEADD('day', -1, CURRENT_TIMESTAMP())) AS AVG_QUERY_SEC_24H,
    
    -- Storage Metrics
    (SELECT ROUND(AVG(STORAGE_BYTES + STAGE_BYTES + FAILSAFE_BYTES)/1024/1024/1024/1024, 4) 
     FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE 
     WHERE USAGE_DATE >= DATEADD('day', -1, CURRENT_TIMESTAMP())) AS STORAGE_TB;

-- 9.3 Weekly Trend Analysis
CREATE OR REPLACE VIEW V_WEEKLY_TRENDS AS
SELECT
    DATE_TRUNC('week', START_TIME) AS WEEK_START,
    COUNT(*) AS QUERY_COUNT,
    COUNT(DISTINCT USER_NAME) AS UNIQUE_USERS,
    COUNT(DISTINCT WAREHOUSE_NAME) AS WAREHOUSES_USED,
    ROUND(AVG(TOTAL_ELAPSED_TIME)/1000, 2) AS AVG_QUERY_SEC,
    ROUND(SUM(BYTES_SCANNED)/1024/1024/1024/1024, 4) AS TB_SCANNED,
    SUM(CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    ROUND(SUM(CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0 / 
          NULLIF(COUNT(*), 0), 2) AS SUCCESS_RATE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('week', -12, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('week', START_TIME)
ORDER BY WEEK_START DESC;

-- 9.4 Cost Efficiency Metrics
CREATE OR REPLACE VIEW V_COST_EFFICIENCY AS
SELECT
    DATE_TRUNC('day', qh.START_TIME) AS REPORT_DATE,
    COUNT(*) AS QUERY_COUNT,
    ROUND(SUM(wm.CREDITS_USED), 4) AS TOTAL_CREDITS,
    ROUND(SUM(wm.CREDITS_USED) / NULLIF(COUNT(*), 0), 6) AS CREDITS_PER_QUERY,
    ROUND(SUM(qh.BYTES_SCANNED)/1024/1024/1024/1024, 4) AS TB_SCANNED,
    ROUND(SUM(wm.CREDITS_USED) / NULLIF(SUM(qh.BYTES_SCANNED)/1024/1024/1024/1024, 0), 4) AS CREDITS_PER_TB
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY wm
    ON qh.WAREHOUSE_NAME = wm.WAREHOUSE_NAME
    AND DATE_TRUNC('hour', qh.START_TIME) = DATE_TRUNC('hour', wm.START_TIME)
WHERE qh.START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('day', qh.START_TIME)
ORDER BY REPORT_DATE DESC;

-- 9.5 SLA Compliance Dashboard
CREATE OR REPLACE VIEW V_SLA_COMPLIANCE AS
WITH sla_metrics AS (
    SELECT
        DATE_TRUNC('day', START_TIME) AS REPORT_DATE,
        -- Query SLA: 95% of queries complete in < 60 seconds
        ROUND(SUM(CASE WHEN TOTAL_ELAPSED_TIME < 60000 THEN 1 ELSE 0 END) * 100.0 / 
              NULLIF(COUNT(*), 0), 2) AS QUERIES_UNDER_60S_PCT,
        -- Availability SLA: 99.9% query success
        ROUND(SUM(CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0 / 
              NULLIF(COUNT(*), 0), 4) AS QUERY_SUCCESS_PCT,
        -- Queue SLA: 90% of queries with < 5 second queue time
        ROUND(SUM(CASE WHEN QUEUED_OVERLOAD_TIME < 5000 THEN 1 ELSE 0 END) * 100.0 / 
              NULLIF(COUNT(*), 0), 2) AS QUERIES_LOW_QUEUE_PCT
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    GROUP BY DATE_TRUNC('day', START_TIME)
)
SELECT
    REPORT_DATE,
    QUERIES_UNDER_60S_PCT,
    CASE WHEN QUERIES_UNDER_60S_PCT >= 95 THEN 'MET' ELSE 'MISSED' END AS PERFORMANCE_SLA,
    QUERY_SUCCESS_PCT,
    CASE WHEN QUERY_SUCCESS_PCT >= 99.9 THEN 'MET' ELSE 'MISSED' END AS AVAILABILITY_SLA,
    QUERIES_LOW_QUEUE_PCT,
    CASE WHEN QUERIES_LOW_QUEUE_PCT >= 90 THEN 'MET' ELSE 'MISSED' END AS QUEUE_SLA
FROM sla_metrics
ORDER BY REPORT_DATE DESC;

/*
================================================================================
SECTION 10: GOVERNANCE, AUTOMATION & STANDARDIZATION
================================================================================
PURPOSE: Implement governance policies, automate routine operations,
         and ensure standardization across the platform.

KEY METRICS:
- Policy compliance rates
- Automation success rates
- Standardization coverage
- Governance violations

DATA SOURCES:
- Custom governance tables
- Policy configurations
- Automation logs
================================================================================
*/

-- 10.1 Governance Policy Configuration
CREATE TABLE IF NOT EXISTS T_GOVERNANCE_POLICIES (
    POLICY_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    POLICY_NAME VARCHAR(255),
    POLICY_CATEGORY VARCHAR(50),  -- NAMING, ACCESS, DATA_RETENTION, COST, SECURITY
    POLICY_DESCRIPTION VARCHAR(4000),
    ENFORCEMENT_LEVEL VARCHAR(20),  -- ADVISORY, MANDATORY, BLOCKING
    CHECK_QUERY VARCHAR(8000),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 10.2 Governance Audit Log
CREATE TABLE IF NOT EXISTS T_GOVERNANCE_AUDIT_LOG (
    AUDIT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    POLICY_ID NUMBER,
    CHECK_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLIANT_COUNT NUMBER,
    NON_COMPLIANT_COUNT NUMBER,
    COMPLIANCE_RATE NUMBER,
    NON_COMPLIANT_OBJECTS VARIANT
);

-- 10.3 Insert Standard Governance Policies
INSERT INTO T_GOVERNANCE_POLICIES (POLICY_NAME, POLICY_CATEGORY, POLICY_DESCRIPTION, ENFORCEMENT_LEVEL, CHECK_QUERY)
SELECT 'WAREHOUSE_AUTO_SUSPEND', 'COST', 'All warehouses must have AUTO_SUSPEND enabled (max 600 seconds)', 'MANDATORY',
       'SELECT WAREHOUSE_NAME FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSES WHERE AUTO_SUSPEND_ENABLED = FALSE OR AUTO_SUSPEND > 600'
WHERE NOT EXISTS (SELECT 1 FROM T_GOVERNANCE_POLICIES WHERE POLICY_NAME = 'WAREHOUSE_AUTO_SUSPEND');

INSERT INTO T_GOVERNANCE_POLICIES (POLICY_NAME, POLICY_CATEGORY, POLICY_DESCRIPTION, ENFORCEMENT_LEVEL, CHECK_QUERY)
SELECT 'TABLE_COMMENT_REQUIRED', 'METADATA', 'All tables must have comments/descriptions', 'ADVISORY',
       'SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES WHERE COMMENT IS NULL AND DELETED IS NULL'
WHERE NOT EXISTS (SELECT 1 FROM T_GOVERNANCE_POLICIES WHERE POLICY_NAME = 'TABLE_COMMENT_REQUIRED');

INSERT INTO T_GOVERNANCE_POLICIES (POLICY_NAME, POLICY_CATEGORY, POLICY_DESCRIPTION, ENFORCEMENT_LEVEL, CHECK_QUERY)
SELECT 'QUERY_TAG_USAGE', 'STANDARDIZATION', 'Production queries should use query tags', 'ADVISORY',
       'SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE QUERY_TAG IS NULL AND START_TIME >= DATEADD(day, -1, CURRENT_TIMESTAMP())'
WHERE NOT EXISTS (SELECT 1 FROM T_GOVERNANCE_POLICIES WHERE POLICY_NAME = 'QUERY_TAG_USAGE');

-- 10.4 Naming Convention Compliance
CREATE OR REPLACE VIEW V_NAMING_CONVENTION_COMPLIANCE AS
SELECT
    'DATABASE' AS OBJECT_TYPE,
    DATABASE_NAME AS OBJECT_NAME,
    CASE 
        WHEN DATABASE_NAME RLIKE '^[A-Z][A-Z0-9_]*$' THEN 'COMPLIANT'
        ELSE 'NON_COMPLIANT'
    END AS NAMING_STATUS,
    'Must be uppercase, start with letter, contain only letters, numbers, underscores' AS CONVENTION
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASES
WHERE DELETED IS NULL

UNION ALL

SELECT
    'TABLE' AS OBJECT_TYPE,
    TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME AS OBJECT_NAME,
    CASE 
        WHEN TABLE_NAME RLIKE '^[A-Z][A-Z0-9_]*$' THEN 'COMPLIANT'
        ELSE 'NON_COMPLIANT'
    END AS NAMING_STATUS,
    'Must be uppercase, start with letter, contain only letters, numbers, underscores' AS CONVENTION
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES
WHERE DELETED IS NULL
    AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA');

-- 10.5 Resource Usage Governance
CREATE OR REPLACE VIEW V_RESOURCE_GOVERNANCE AS
SELECT
    WAREHOUSE_NAME,
    MAX(WAREHOUSE_SIZE) AS MAX_SIZE_USED,
    SUM(CREDITS_USED) AS TOTAL_CREDITS_7D,
    COUNT(DISTINCT DATE_TRUNC('day', START_TIME)) AS ACTIVE_DAYS,
    ROUND(AVG(CREDITS_USED), 4) AS AVG_HOURLY_CREDITS,
    CASE
        WHEN SUM(CREDITS_USED) > 100 THEN 'HIGH_CONSUMPTION'
        WHEN SUM(CREDITS_USED) > 50 THEN 'MODERATE_CONSUMPTION'
        ELSE 'LOW_CONSUMPTION'
    END AS CONSUMPTION_TIER
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_CREDITS_7D DESC;

-- 10.6 Automation: Cleanup Procedure for Old Data
CREATE OR REPLACE PROCEDURE SP_CLEANUP_OBSERVABILITY_DATA(P_RETENTION_DAYS NUMBER)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    V_DELETED_ALERTS NUMBER;
    V_DELETED_QUALITY NUMBER;
    V_DELETED_AUDIT NUMBER;
BEGIN
    -- Cleanup old alert history
    DELETE FROM T_ALERT_HISTORY 
    WHERE TRIGGERED_AT < DATEADD('day', -P_RETENTION_DAYS, CURRENT_TIMESTAMP());
    V_DELETED_ALERTS := SQLROWCOUNT;
    
    -- Cleanup old quality results
    DELETE FROM T_DATA_QUALITY_RESULTS 
    WHERE EXECUTION_TIME < DATEADD('day', -P_RETENTION_DAYS, CURRENT_TIMESTAMP());
    V_DELETED_QUALITY := SQLROWCOUNT;
    
    -- Cleanup old audit logs
    DELETE FROM T_GOVERNANCE_AUDIT_LOG 
    WHERE CHECK_TIME < DATEADD('day', -P_RETENTION_DAYS, CURRENT_TIMESTAMP());
    V_DELETED_AUDIT := SQLROWCOUNT;
    
    RETURN 'Cleanup completed. Deleted: ' || V_DELETED_ALERTS || ' alerts, ' || 
           V_DELETED_QUALITY || ' quality results, ' || V_DELETED_AUDIT || ' audit logs';
END;
$$;

-- 10.7 Task: Scheduled Cleanup (Run weekly)
CREATE OR REPLACE TASK TASK_WEEKLY_CLEANUP
    WAREHOUSE = OBSERVABILITY_WH
    SCHEDULE = 'USING CRON 0 2 * * SUN America/Los_Angeles'  -- Every Sunday at 2 AM
AS
    CALL SP_CLEANUP_OBSERVABILITY_DATA(90);  -- Keep 90 days of data

-- 10.8 Automation Task: Daily Health Check
CREATE OR REPLACE TASK TASK_DAILY_HEALTH_CHECK
    WAREHOUSE = OBSERVABILITY_WH
    SCHEDULE = 'USING CRON 0 6 * * * America/Los_Angeles'  -- Every day at 6 AM
AS
    INSERT INTO T_ALERT_HISTORY (ALERT_NAME, SEVERITY, STATUS, NOTES)
    SELECT 
        'DAILY_HEALTH_CHECK',
        CASE 
            WHEN OVERALL_HEALTH_SCORE >= 95 THEN 'LOW'
            WHEN OVERALL_HEALTH_SCORE >= 85 THEN 'MEDIUM'
            ELSE 'HIGH'
        END,
        'TRIGGERED',
        'Daily health score: ' || OVERALL_HEALTH_SCORE || '% | Query Success: ' || QUERY_SUCCESS_RATE || '%'
    FROM V_PLATFORM_HEALTH_SCORE;

/*
================================================================================
SECTION 11: FRAMEWORK SUMMARY & USAGE GUIDE
================================================================================

QUICK REFERENCE - KEY VIEWS BY DOMAIN:

1. PLATFORM PERFORMANCE:
   - V_WAREHOUSE_PERFORMANCE_SUMMARY
   - V_QUERY_PERFORMANCE_DISTRIBUTION
   - V_LONG_RUNNING_QUERIES
   - V_COMPILATION_EXECUTION_ANALYSIS

2. PIPELINE RELIABILITY:
   - V_TASK_EXECUTION_SUMMARY
   - V_FAILED_TASKS_DETAIL
   - V_TABLE_FRESHNESS
   - V_COPY_HISTORY_SUMMARY

3. FINOPS & COST:
   - V_CREDIT_CONSUMPTION_WAREHOUSE
   - V_CREDIT_CONSUMPTION_USER
   - V_SERVERLESS_COSTS
   - V_MONTHLY_COST_SUMMARY

4. DATA QUALITY:
   - T_DATA_QUALITY_RULES (Configuration)
   - T_DATA_QUALITY_RESULTS (Results)
   - V_SCHEMA_CHANGES
   - V_TABLE_STATISTICS

5. SECURITY & ACCESS:
   - V_LOGIN_ACTIVITY
   - V_FAILED_LOGINS
   - V_DATA_ACCESS_PATTERNS
   - V_PRIVILEGE_CHANGES

6. METADATA & LINEAGE:
   - V_OBJECT_DEPENDENCIES
   - V_COLUMN_LINEAGE
   - V_TAG_COVERAGE
   - V_OBJECT_CATALOG

7. USER BEHAVIOR:
   - V_USER_ACTIVITY_HEATMAP
   - V_QUERY_TYPE_DISTRIBUTION
   - V_CONCURRENCY_ANALYSIS
   - V_USER_ENGAGEMENT_SCORE

8. ALERTING:
   - T_ALERT_CONFIG
   - T_ALERT_HISTORY
   - ALERT_LONG_RUNNING_QUERY
   - ALERT_FAILED_TASK

9. EXECUTIVE DASHBOARDS:
   - V_PLATFORM_HEALTH_SCORE
   - V_EXECUTIVE_SUMMARY
   - V_WEEKLY_TRENDS
   - V_SLA_COMPLIANCE

10. GOVERNANCE:
    - T_GOVERNANCE_POLICIES
    - T_GOVERNANCE_AUDIT_LOG
    - V_NAMING_CONVENTION_COMPLIANCE
    - V_RESOURCE_GOVERNANCE

================================================================================
ACTIVATION CHECKLIST:
================================================================================
[ ] 1. Run all CREATE statements to set up objects
[ ] 2. Resume alerts: ALTER ALERT <alert_name> RESUME;
[ ] 3. Resume tasks: ALTER TASK <task_name> RESUME;
[ ] 4. Configure notification integrations for alerts
[ ] 5. Set up Snowsight dashboards using the views
[ ] 6. Configure data quality DMFs for critical tables
[ ] 7. Test all views return expected data
[ ] 8. Schedule periodic governance audits
================================================================================
*/

-- Show all created objects
SHOW VIEWS IN SCHEMA OBSERVABILITY;
SHOW TABLES IN SCHEMA OBSERVABILITY;
SHOW ALERTS IN SCHEMA OBSERVABILITY;
SHOW TASKS IN SCHEMA OBSERVABILITY;
SHOW PROCEDURES IN SCHEMA OBSERVABILITY;




